@startuml

class Game {
    +Player1: Player 
    +Player2: Player 
    -Turn: Int
    +StartGame()
    +QuitGame()
    +DisplayScore()
    -UpdateScore()
}

class Board {
    +BoardGrid: List
    +Fleet: Fleet [1]
    +PrintBoard()
    +UpdateBoard()
    +PlaceShips()
}

class Player {
    +Score: Int
    +Board: Board [1]
    +UpdateScore()
    +ResetBoard()
    +GetMove(): Tuple
}

class Ship {
    -{static}SIZE: Int
    +Health: List
    +IsSunk: Bool
    +UpdateHealth(hitIndex)
    +SinkShip()
}

class Battleship {
    -{static}SIZE: int = 5 
}

class Destroyer {
    -{static}SIZE: int = 3 
}

class Minesweeper {
    -{static}SIZE: int = 2 
}

class Fleet {
    + Battleship: Battleship [1]
    + Destroyer: Destroyer [1]
    + Minesweeper: Minesweeper [2]
}

Player "2 "-down-* Game
Board -right-* Player
Fleet -right-* Board

Battleship --* Fleet
Destroyer --* Fleet
Minesweeper --* Fleet

Battleship -up-|> Ship
Destroyer -up-|> Ship
Minesweeper -up-|> Ship

@enduml